language: node_js
node_js:
  - 12

sudo: required

services:
  - docker

script:
  - ./bin/build.js --type=all
deploy:
  provider: heroku
  api_key:
    secure: 3a31416a44565544905dbb9489a635901e5559c1
    app: olympia
